### PR TITLE
Remove usage of deprecated methods

### PR DESCRIPTION
**Pull request by slavik-lvovsky**
Remove usage of "settle" deprecated method used in allSettled and
allResolved

### CODE REVIEW

**Comment by lextiz** [comment]
Looks good to me, aligned with http://bluebirdjs.com/docs/api/reflect.html. I would appreciate if @petkaantonov would have a short look at this change before merge to make sure the implementation is right.

**Comment by petkaantonov** [comment]
.value() doesnt make sense

**Comment by lextiz** [comment]
Thanks @petkaantonov! @drujik1977 please just remove the ".value()", https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map will do the job.

**Comment by lextiz** [comment]
My wrong: using .map() only will do the job only for one use case out of two: Q's allSettled accepts both Array<Promise> and Promise<Array<Promise>>(https://github.com/kriskowal/q/blob/v1/q.js#L1689), .value() is needed for the second case. In first case https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map would be used, in second http://bluebirdjs.com/docs/api/promise.map.html. @petkaantonov Maybe I do not understand something, but it looks like actually .value() is needed, because using .map() on "this" of type Promise<Array<Promise>> resolves (or rejects) promises inside the array, but the mapper function expects to receive a promise, not a value. @drujik1977 Anyway it is a good idea to check http://bluebirdjs.com/docs/api/isfulfilled.html before using .value() method. I think you have to check if "this" is a promise and then get its value, in case "this" is an array, .map() will do the job.

**Comment by lextiz** [comment]
Looks good, will merge today, if there are no objections.

**Pull request merged**
