### PR TITLE
Updated dependency to bluebird to version 3.3.1

### PR DESCRIPTION
**Pull request by lextiz**
- Progess method was removed
- Source path changed

### CODE REVIEW

**Comment by esamattis** [comment]
<strike>This breaks `promise.progress(onProgress)` because the equivalent promise progression api in Bluebird has been completely removed in 3.0.

More info http://bluebirdjs.com/docs/deprecated-apis.html#progression</strike>

EDIT:  Just realized that it was documented in the changes.

**Comment by lextiz** [comment]
That is right. Does it mean that bluebird dependency should not be upgraded? I think an version of bluebird-q should be tagged before merging this change, this would allow people who need progress method to use older version of bluebird.

**Comment by esamattis** [comment]
Yeah, this is a breaking change and it would require a major version bump. 

Or better yet the progress method should be implemented in the bluebird-q code.

**Comment by lextiz** [comment]
Do you have any ideas on how to implement this? Is this possible without changing bluebird code? Also there are no tagged versions yet...

**Comment by petkaantonov** [comment]
>  Or better yet the progress method should be implemented in the bluebird-q code.

This is out of scope for this library, it's just supposed to be glue code and not contain any original implementations.

**Pull request merged**
